#!/bin/bash

set -o nounset

VERSION='1.1.1'
DIR="idba-${VERSION}"

TMP=$(mktemp -d)

cd ${TMP}
tar xzf "/tmp/${DIR}.tar.gz"
cd ${DIR}

# Required to allow for longer read lengths
sed --in-place 's/kMaxShortSequence = 128;/kMaxShortSequence = 1024;/' src/sequence/short_sequence.h

./configure
make

mv bin /usr/local/idba
