#!/bin/bash

set -o xtrace
set -o errexit
set -o nounset

# The first argument is the location of the reads in the container filesystem.
# The will be present in a read-only directory
READS=$1

# The second argument is a directory with write-access where the final
# assembly should be written to.
DIR=$2
LOG=$DIR/log.txt

# The assembly should be written to the file "contigs.fa" in the output directory
ASSEMBLY=$DIR/contigs.fa

TMP_DIR=`mktemp -d`
gunzip $READS --stdout > $TMP_DIR/reads.fq
cd $TMP_DIR
fq2fa --paired reads.fq reads.fa

idba --out $TMP_DIR --read $TMP_DIR/reads.fa 2> $LOG 1>&2

OUTPUT=`ls -t $TMP_DIR/graph-*.fa | head -n 1`

cp $OUTPUT $ASSEMBLY
