#!/bin/bash

set -o errexit
set -o nounset

# Destination output directory
DIR=$3

# Set up logging
LOG=$DIR/log.txt
exec  > >(tee ${LOG})
exec 2>&1
set -o xtrace

# Destination contigs file
ASSEMBLY=$DIR/contigs.fa

# Source reads in this container
INPUTS=$2

# Determine which process to run
PROC=$1
CMD=$(egrep ^${PROC}: /Procfile | cut -f 2 -d ':')

if [[ -z ${CMD} ]]; then
  echo "Abort, no proc found for ${PROC}."
  exit 1
fi

# Decompress reads
TMP=$(mktemp -d)
READS="$TMP/reads.fq"

mkfifo $READS
gunzip $INPUTS --stdout > $READS &

eval ${CMD}

OUTPUT=$(ls -t $TMP/graph-*.fa | head -n 1)
cp $OUTPUT $ASSEMBLY
